---
title: "Naiive Bayes Classifier"
author: "Joe Turner"
date: "24 April 2017"
output: pdf_document
---

```{r}

library(rpart)
library(tree)
library(randomForest)
library(e1071)
library(plyr)
library(vegan)
library(doBy)
library(rgdal)
library(clustsig)
library(gdata)
library(ggplot2)
library(scales)
library(ggrepel)
library(RColorBrewer)
library(reshape2)
library(reshape)
library(grid)
library(dplR)
library(gridExtra)
library(Hmisc)
library(corrplot)
library(PerformanceAnalytics)
library(raster)
library(gmodels)
st.err <- function(x) {sd(x)/sqrt(length(x))}

setwd("C:/OneDrive/C3_Map")
GT <- read.csv("14_GIS_GT_Intercept_5m_9999_Removed_L3EDIT.csv", header = TRUE)
Helby <- read.csv("15_HelbyBanks_GT_5m_L3EDIT.csv", header = TRUE)
Tanta <- read.csv("16_Tantabiddi_GT_5m_L3EDIT.csv", header = TRUE)
Mgrove <- read.csv("17_Mangrove_GT_5m_L3EDIT.csv", header = TRUE)
South <- read.csv("18_SouthSite_GT_5m_L3EDIT.csv", header = TRUE)

setwd("C:/OneDrive/C3_Map/PointsForPrediction")

HBpoints <- read.csv("Helby_Predict_5m.csv", header = TRUE)
TBpoints <- read.csv("Tanta_Predict_5m.csv", header = TRUE)
MGpoints <- read.csv("Mangrove_Predict_5m.csv", header = TRUE)
SSpoints <- read.csv("South_Predict_5m.csv", header = TRUE)
points1 <- read.csv("AllSites_Predict_5m_1.csv", header = TRUE)
points2 <- read.csv("AllSites_Predict_5m_2.csv", header = TRUE)
points3 <- read.csv("AllSites_Predict_5m_3.csv", header = TRUE)

```



```{r select training and evaluation data}

set.seed(387)  

# For all data
size.modeldata <- round(0.75 * nrow(GT))
model  <- GT[sample ( 1:nrow(GT), size.modeldata, replace = FALSE),]
test <- GT[- c( sample ( 1:nrow(GT), size.modeldata, replace = FALSE) ),]

# For Helby Banks
HBsize.modeldata <- round(0.75 * nrow(Helby))
HBmodel  <- Helby[sample ( 1:nrow(Helby), HBsize.modeldata, replace = FALSE),]
HBtest <- Helby[- c( sample ( 1:nrow(Helby), HBsize.modeldata, replace = FALSE) ),]

# For Tantabiddi
TBsize.modeldata <- round(0.75 * nrow(Tanta))
TBmodel  <- Tanta[sample ( 1:nrow(Tanta), TBsize.modeldata, replace = FALSE),]
TBtest <- Tanta[- c( sample ( 1:nrow(Tanta), TBsize.modeldata, replace = FALSE) ),]

# For Mangrove
MGsize.modeldata <- round(0.75 * nrow(Mgrove))
MGmodel  <- Mgrove[sample ( 1:nrow(Mgrove), MGsize.modeldata, replace = FALSE),]
MGtest <- Mgrove[- c( sample ( 1:nrow(Mgrove), MGsize.modeldata, replace = FALSE) ),]

# For Southern Site
SSsize.modeldata <- round(0.75 * nrow(South))
SSmodel  <- South[sample ( 1:nrow(South), SSsize.modeldata, replace = FALSE),]
SStest <- South[- c( sample ( 1:nrow(South), SSsize.modeldata, replace = FALSE) ),]


```


```{r}

# http://www.learnbymarketing.com/tutorials/naive-bayes-in-r/
# https://www.youtube.com/watch?v=-SeyrC4yZF4
# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4930525/


##########################
#### LEVEL 1 HABITATS ####
##########################

setwd("C:/OneDrive/C3_Map/NB_Outputs/Figures")
set.seed(415)

L1_Hab.naiveBayes <- naiveBayes(as.factor(L1_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= model)

L1_Hab.naiveBayes
summary(L1_Hab.naiveBayes)
str(L1_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/ALL_L1_Hab.txt")
L1_Hab.naiveBayes 
sink()


true.type = as.factor(test[,13])
predicted = predict(L1_Hab.naiveBayes, test,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.type,predicted), "1_NB_Lv1_MisclassMatrix.csv")

# need to edit, look at http://trevorstephens.com/kaggle-titanic-tutorial/r-part-5-random-forests/
PredictionL1_Hab <- predict(L1_Hab.naiveBayes, test)
submitL1_Hab <- data.frame(HabType = test$L1_Hab, PredictedL1_Hab = PredictionL1_Hab, X = test$Lat, Y = test$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitL1_Hab, file = "L1_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

L1_Hab.NB.predict <- predict(L1_Hab.naiveBayes, points1, type="class")
L1_Hab.predict <- as.data.frame(L1_Hab.NB.predict)
pred.L1_Hab <- as.data.frame(cbind(points1$Long, points1$Lat, L1_Hab.predict))
pred.L1_Hab$L1_Hab.NB.predict <- as.numeric(as.character(pred.L1_Hab$L1_Hab.NB.predict))
names(pred.L1_Hab) <- c("X","Y", "predL1_Hab")


L1_Hab.NB.predict2 <- predict(L1_Hab.naiveBayes, points2)
L1_Hab.predict2 <- as.data.frame(L1_Hab.NB.predict2)
pred.L1_Hab2 <- as.data.frame(cbind(points2$Long, points2$Lat,  L1_Hab.predict2))
pred.L1_Hab2$L1_Hab.NB.predict2 <- as.numeric(as.character(pred.L1_Hab2$L1_Hab.NB.predict2))
names(pred.L1_Hab2) <- c("X","Y", "predL1_Hab")

L1_Hab.NB.predict3 <- predict(L1_Hab.naiveBayes, points3)
L1_Hab.predict3 <- as.data.frame(L1_Hab.NB.predict3)
pred.L1_Hab3 <- as.data.frame(cbind(points3$Long, points3$Lat,  L1_Hab.predict3))
pred.L1_Hab3$L1_Hab.NB.predict3 <- as.numeric(as.character(pred.L1_Hab3$L1_Hab.NB.predict3))
names(pred.L1_Hab3) <- c("X","Y", "predL1_Hab")

############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv1Outputs")

coordinates(pred.L1_Hab) <- ~X+Y
ext <- extent(pred.L1_Hab)
r <- raster(ext=ext,res=0.0000483000000031097)
to_ascii <- rasterize(pred.L1_Hab, r, 'predL1_Hab')
writeRaster(to_ascii,'L1_HabNB.asc', format='ascii', overwrite =TRUE)

coordinates(pred.L1_Hab2) <- ~X+Y
ext2 <- extent(pred.L1_Hab2)
r2 <- raster(ext=ext2,res=0.0000483000000031097)
to_ascii2 <- rasterize(pred.L1_Hab2, r2, 'predL1_Hab')
writeRaster(to_ascii2,'L1_HabNB2.asc', format='ascii', overwrite =TRUE)

coordinates(pred.L1_Hab3) <- ~X+Y
ext3 <- extent(pred.L1_Hab3)
r3 <- raster(ext=ext3,res=0.0000483000000031097)
to_ascii3 <- rasterize(pred.L1_Hab3, r3, 'predL1_Hab')
writeRaster(to_ascii3,'L1_HabNB3.asc', format='ascii', overwrite =TRUE)


#################
## HELBY BANKS ##
#################

HB_L1_Hab.naiveBayes <- naiveBayes(as.factor(L1_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= HBmodel)

HB_L1_Hab.naiveBayes
summary(HB_L1_Hab.naiveBayes)
str(HB_L1_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/HB_L1_Hab.txt")
HB_L1_Hab.naiveBayes 
sink()


true.typeHB = as.factor(HBtest[,13])
predictedHB = predict(HB_L1_Hab.naiveBayes, HBtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeHB,predictedHB), "4_NB_HB_Lv1_MisclassMatrix.csv")

PredictionHB_L1_Hab <- predict(HB_L1_Hab.naiveBayes, HBtest)
submitHB_L1_Hab <- data.frame(HabType = HBtest$L1_Hab, PredictedHB_L1_Hab = PredictionHB_L1_Hab, 
                              X = HBtest$Lat, Y = HBtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitHB_L1_Hab, file = "HB_L1_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

HB_L1_Hab.NB.predict <- predict(HB_L1_Hab.naiveBayes, HBpoints, type="class")
HB_L1_Hab.predict <- as.data.frame(HB_L1_Hab.NB.predict)
pred.HB_L1_Hab <- as.data.frame(cbind(HBpoints$Long, HBpoints$Lat, HB_L1_Hab.predict))
pred.HB_L1_Hab$HB_L1_Hab.NB.predict <- as.numeric(as.character(pred.HB_L1_Hab$HB_L1_Hab.NB.predict))
names(pred.HB_L1_Hab) <- c("X","Y", "predHB_L1_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv1Outputs")

coordinates(pred.HB_L1_Hab) <- ~X+Y
extHB <- extent(pred.HB_L1_Hab)
rHB <- raster(ext=extHB,res=0.0000483000000031097)
to_asciiHB <- rasterize(pred.HB_L1_Hab, rHB, 'predHB_L1_Hab')
writeRaster(to_asciiHB,'HB_L1_HabNB.asc', format='ascii', overwrite =TRUE)




################
## TANTABIDDI ##
################

TB_L1_Hab.naiveBayes <- naiveBayes(as.factor(L1_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= TBmodel)

TB_L1_Hab.naiveBayes
summary(TB_L1_Hab.naiveBayes)
str(TB_L1_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/TB_L1_Hab.txt")
TB_L1_Hab.naiveBayes 
sink()


true.typeTB = as.factor(TBtest[,13])
predictedTB = predict(TB_L1_Hab.naiveBayes, TBtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeTB,predictedTB), "5_NB_TB_Lv1_MisclassMatrix.csv")

PredictionTB_L1_Hab <- predict(TB_L1_Hab.naiveBayes, TBtest)
submitTB_L1_Hab <- data.frame(HabType = TBtest$L1_Hab, PredictedTB_L1_Hab = PredictionTB_L1_Hab, 
                              X = TBtest$Lat, Y = TBtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitTB_L1_Hab, file = "TB_L1_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

TB_L1_Hab.NB.predict <- predict(TB_L1_Hab.naiveBayes, TBpoints, type="class")
TB_L1_Hab.predict <- as.data.frame(TB_L1_Hab.NB.predict)
pred.TB_L1_Hab <- as.data.frame(cbind(TBpoints$Long, TBpoints$Lat, TB_L1_Hab.predict))
pred.TB_L1_Hab$TB_L1_Hab.NB.predict <- as.numeric(as.character(pred.TB_L1_Hab$TB_L1_Hab.NB.predict))
names(pred.TB_L1_Hab) <- c("X","Y", "predTB_L1_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv1Outputs")

coordinates(pred.TB_L1_Hab) <- ~X+Y
extTB <- extent(pred.TB_L1_Hab)
rTB <- raster(ext=extTB,res=0.0000483000000031097)
to_asciiTB <- rasterize(pred.TB_L1_Hab, rTB, 'predTB_L1_Hab')
writeRaster(to_asciiTB,'TB_L1_HabNB.asc', format='ascii', overwrite =TRUE)


##############
## MANGROVE ##
##############

MG_L1_Hab.naiveBayes <- naiveBayes(as.factor(L1_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= MGmodel)

MG_L1_Hab.naiveBayes
summary(MG_L1_Hab.naiveBayes)
str(MG_L1_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/MG_L1_Hab.txt")
MG_L1_Hab.naiveBayes 
sink()


true.typeMG = as.factor(MGtest[,13])
predictedMG = predict(MG_L1_Hab.naiveBayes, MGtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeMG,predictedMG), "4_NB_MG_Lv1_MisclassMatrix.csv")

PredictionMG_L1_Hab <- predict(MG_L1_Hab.naiveBayes, MGtest)
submitMG_L1_Hab <- data.frame(HabType = MGtest$L1_Hab, PredictedMG_L1_Hab = PredictionMG_L1_Hab, 
                              X = MGtest$Lat, Y = MGtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitMG_L1_Hab, file = "MG_L1_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

MG_L1_Hab.NB.predict <- predict(MG_L1_Hab.naiveBayes, MGpoints, type="class")
MG_L1_Hab.predict <- as.data.frame(MG_L1_Hab.NB.predict)
pred.MG_L1_Hab <- as.data.frame(cbind(MGpoints$Long, MGpoints$Lat, MG_L1_Hab.predict))
pred.MG_L1_Hab$MG_L1_Hab.NB.predict <- as.numeric(as.character(pred.MG_L1_Hab$MG_L1_Hab.NB.predict))
names(pred.MG_L1_Hab) <- c("X","Y", "predMG_L1_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv1Outputs")

coordinates(pred.MG_L1_Hab) <- ~X+Y
extMG <- extent(pred.MG_L1_Hab)
rMG <- raster(ext=extMG,res=0.0000483000000031097)
to_asciiMG <- rasterize(pred.MG_L1_Hab, rMG, 'predMG_L1_Hab')
writeRaster(to_asciiMG,'MG_L1_HabNB.asc', format='ascii', overwrite =TRUE)




###################
## SOUTHERN SITE ##
###################

SS_L1_Hab.naiveBayes <- naiveBayes(as.factor(L1_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= SSmodel)

SS_L1_Hab.naiveBayes
summary(SS_L1_Hab.naiveBayes)
str(SS_L1_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/SS_L1_Hab.txt")
SS_L1_Hab.naiveBayes 
sink()


true.typeSS = as.factor(SStest[,13])
predictedSS = predict(SS_L1_Hab.naiveBayes, SStest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeSS,predictedSS), "4_NB_SS_Lv1_MisclassMatrix.csv")

PredictionSS_L1_Hab <- predict(SS_L1_Hab.naiveBayes, SStest)
submitSS_L1_Hab <- data.frame(HabType = SStest$L1_Hab, PredictedSS_L1_Hab = PredictionSS_L1_Hab, 
                              X = SStest$Lat, Y = SStest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitSS_L1_Hab, file = "SS_L1_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

SS_L1_Hab.NB.predict <- predict(SS_L1_Hab.naiveBayes, SSpoints, type="class")
SS_L1_Hab.predict <- as.data.frame(SS_L1_Hab.NB.predict)
pred.SS_L1_Hab <- as.data.frame(cbind(SSpoints$Long, SSpoints$Lat, SS_L1_Hab.predict))
pred.SS_L1_Hab$SS_L1_Hab.NB.predict <- as.numeric(as.character(pred.SS_L1_Hab$SS_L1_Hab.NB.predict))
names(pred.SS_L1_Hab) <- c("X","Y", "predSS_L1_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv1Outputs")

coordinates(pred.SS_L1_Hab) <- ~X+Y
extSS <- extent(pred.SS_L1_Hab)
rSS <- raster(ext=extSS,res=0.000048500000005447)
to_asciiSS <- rasterize(pred.SS_L1_Hab, rSS, 'predSS_L1_Hab')
writeRaster(to_asciiSS,'SS_L1_HabNB.asc', format='ascii', overwrite =TRUE)


```








```{r}


##########################
#### LEVEL 2 HABITATS ####
##########################

setwd("C:/OneDrive/C3_Map/NB_Outputs/Figures")
set.seed(415)

L2_Hab.naiveBayes <- naiveBayes(as.factor(L2_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= model)

L2_Hab.naiveBayes
summary(L2_Hab.naiveBayes)
str(L2_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/ALL_L2_Hab.txt")
L2_Hab.naiveBayes 
sink()


true.type = as.factor(test[,14])
predicted = predict(L2_Hab.naiveBayes, test,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.type,predicted), "2_NB_Lv2_MisclassMatrix.csv")

# need to edit, look at http://trevorstephens.com/kaggle-titanic-tutorial/r-part-5-random-forests/
PredictionL2_Hab <- predict(L2_Hab.naiveBayes, test)
submitL2_Hab <- data.frame(HabType = test$L2_Hab, PredictedL2_Hab = PredictionL2_Hab, X = test$Lat, Y = test$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitL2_Hab, file = "L2_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

L2_Hab.NB.predict <- predict(L2_Hab.naiveBayes, points1, type="class")
L2_Hab.predict <- as.data.frame(L2_Hab.NB.predict)
pred.L2_Hab <- as.data.frame(cbind(points1$Long, points1$Lat, L2_Hab.predict))
pred.L2_Hab$L2_Hab.NB.predict <- as.numeric(as.character(pred.L2_Hab$L2_Hab.NB.predict))
names(pred.L2_Hab) <- c("X","Y", "predL2_Hab")


L2_Hab.NB.predict2 <- predict(L2_Hab.naiveBayes, points2, type="class")
L2_Hab.predict2 <- as.data.frame(L2_Hab.NB.predict2)
pred.L2_Hab2 <- as.data.frame(cbind(points2$Long, points2$Lat,  L2_Hab.predict2))
pred.L2_Hab2$L2_Hab.NB.predict2 <- as.numeric(as.character(pred.L2_Hab2$L2_Hab.NB.predict2))
names(pred.L2_Hab2) <- c("X","Y", "predL2_Hab")

L2_Hab.NB.predict3 <- predict(L2_Hab.naiveBayes, points3, type="class")
L2_Hab.predict3 <- as.data.frame(L2_Hab.NB.predict3)
pred.L2_Hab3 <- as.data.frame(cbind(points3$Long, points3$Lat,  L2_Hab.predict3))
pred.L2_Hab3$L2_Hab.NB.predict3 <- as.numeric(as.character(pred.L2_Hab3$L2_Hab.NB.predict3))
names(pred.L2_Hab3) <- c("X","Y", "predL2_Hab")

############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv2Outputs")

coordinates(pred.L2_Hab) <- ~X+Y
ext <- extent(pred.L2_Hab)
r <- raster(ext=ext,res=0.0000483000000031097)
to_ascii <- rasterize(pred.L2_Hab, r, 'predL2_Hab')
writeRaster(to_ascii,'L2_HabNB.asc', format='ascii', overwrite =TRUE)

coordinates(pred.L2_Hab2) <- ~X+Y
ext2 <- extent(pred.L2_Hab2)
r2 <- raster(ext=ext2,res=0.0000483000000031097)
to_ascii2 <- rasterize(pred.L2_Hab2, r2, 'predL2_Hab')
writeRaster(to_ascii2,'L2_HabNB2.asc', format='ascii', overwrite =TRUE)

coordinates(pred.L2_Hab3) <- ~X+Y
ext3 <- extent(pred.L2_Hab3)
r3 <- raster(ext=ext3,res=0.0000483000000031097)
to_ascii3 <- rasterize(pred.L2_Hab3, r3, 'predL2_Hab')
writeRaster(to_ascii3,'L2_HabNB3.asc', format='ascii', overwrite =TRUE)


#################
## HELBY BANKS ##
#################

HB_L2_Hab.naiveBayes <- naiveBayes(as.factor(L2_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= HBmodel)

HB_L2_Hab.naiveBayes
summary(HB_L2_Hab.naiveBayes)
str(HB_L2_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/HB_L2_Hab.txt")
HB_L2_Hab.naiveBayes 
sink()


true.typeHB = as.factor(HBtest[,14])
predictedHB = predict(HB_L2_Hab.naiveBayes, HBtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeHB,predictedHB), "8_NB_HB_Lv2_MisclassMatrix.csv")

PredictionHB_L2_Hab <- predict(HB_L2_Hab.naiveBayes, HBtest)
submitHB_L2_Hab <- data.frame(HabType = HBtest$L2_Hab, PredictedHB_L2_Hab = PredictionHB_L2_Hab, 
                              X = HBtest$Lat, Y = HBtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitHB_L2_Hab, file = "HB_L2_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

HB_L2_Hab.NB.predict <- predict(HB_L2_Hab.naiveBayes, HBpoints, type="class")
HB_L2_Hab.predict <- as.data.frame(HB_L2_Hab.NB.predict)
pred.HB_L2_Hab <- as.data.frame(cbind(HBpoints$Long, HBpoints$Lat, HB_L2_Hab.predict))
pred.HB_L2_Hab$HB_L2_Hab.NB.predict <- as.numeric(as.character(pred.HB_L2_Hab$HB_L2_Hab.NB.predict))
names(pred.HB_L2_Hab) <- c("X","Y", "predHB_L2_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv2Outputs")

coordinates(pred.HB_L2_Hab) <- ~X+Y
extHB <- extent(pred.HB_L2_Hab)
rHB <- raster(ext=extHB,res=0.0000483000000031097)
to_asciiHB <- rasterize(pred.HB_L2_Hab, rHB, 'predHB_L2_Hab')
writeRaster(to_asciiHB,'HB_L2_HabNB.asc', format='ascii', overwrite =TRUE)




################
## TANTABIDDI ##
################

TB_L2_Hab.naiveBayes <- naiveBayes(as.factor(L2_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= TBmodel)

TB_L2_Hab.naiveBayes
summary(TB_L2_Hab.naiveBayes)
str(TB_L2_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/TB_L2_Hab.txt")
TB_L2_Hab.naiveBayes 
sink()


true.typeTB = as.factor(TBtest[,14])
predictedTB = predict(TB_L2_Hab.naiveBayes, TBtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeTB,predictedTB), "9_NB_TB_Lv2_MisclassMatrix.csv")

PredictionTB_L2_Hab <- predict(TB_L2_Hab.naiveBayes, TBtest)
submitTB_L2_Hab <- data.frame(HabType = TBtest$L2_Hab, PredictedTB_L2_Hab = PredictionTB_L2_Hab, 
                              X = TBtest$Lat, Y = TBtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitTB_L2_Hab, file = "TB_L2_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

TB_L2_Hab.NB.predict <- predict(TB_L2_Hab.naiveBayes, TBpoints, type="class")
TB_L2_Hab.predict <- as.data.frame(TB_L2_Hab.NB.predict)
pred.TB_L2_Hab <- as.data.frame(cbind(TBpoints$Long, TBpoints$Lat, TB_L2_Hab.predict))
pred.TB_L2_Hab$TB_L2_Hab.NB.predict <- as.numeric(as.character(pred.TB_L2_Hab$TB_L2_Hab.NB.predict))
names(pred.TB_L2_Hab) <- c("X","Y", "predTB_L2_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv2Outputs")

coordinates(pred.TB_L2_Hab) <- ~X+Y
extTB <- extent(pred.TB_L2_Hab)
rTB <- raster(ext=extTB,res=0.0000483000000031097)
to_asciiTB <- rasterize(pred.TB_L2_Hab, rTB, 'predTB_L2_Hab')
writeRaster(to_asciiTB,'TB_L2_HabNB.asc', format='ascii', overwrite =TRUE)


##############
## MANGROVE ##
##############

MG_L2_Hab.naiveBayes <- naiveBayes(as.factor(L2_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= MGmodel)

MG_L2_Hab.naiveBayes
summary(MG_L2_Hab.naiveBayes)
str(MG_L2_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/MG_L2_Hab.txt")
MG_L2_Hab.naiveBayes 
sink()


true.typeMG = as.factor(MGtest[,14])
predictedMG = predict(MG_L2_Hab.naiveBayes, MGtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeMG,predictedMG), "10_NB_MG_Lv2_MisclassMatrix.csv")

PredictionMG_L2_Hab <- predict(MG_L2_Hab.naiveBayes, MGtest)
submitMG_L2_Hab <- data.frame(HabType = MGtest$L2_Hab, PredictedMG_L2_Hab = PredictionMG_L2_Hab, 
                              X = MGtest$Lat, Y = MGtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitMG_L2_Hab, file = "MG_L2_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

MG_L2_Hab.NB.predict <- predict(MG_L2_Hab.naiveBayes, MGpoints, type="class")
MG_L2_Hab.predict <- as.data.frame(MG_L2_Hab.NB.predict)
pred.MG_L2_Hab <- as.data.frame(cbind(MGpoints$Long, MGpoints$Lat, MG_L2_Hab.predict))
pred.MG_L2_Hab$MG_L2_Hab.NB.predict <- as.numeric(as.character(pred.MG_L2_Hab$MG_L2_Hab.NB.predict))
names(pred.MG_L2_Hab) <- c("X","Y", "predMG_L2_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv2Outputs")

coordinates(pred.MG_L2_Hab) <- ~X+Y
extMG <- extent(pred.MG_L2_Hab)
rMG <- raster(ext=extMG,res=0.0000483000000031097)
to_asciiMG <- rasterize(pred.MG_L2_Hab, rMG, 'predMG_L2_Hab')
writeRaster(to_asciiMG,'MG_L2_HabNB.asc', format='ascii', overwrite =TRUE)




###################
## SOUTHERN SITE ##
###################

SS_L2_Hab.naiveBayes <- naiveBayes(as.factor(L2_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= SSmodel)

SS_L2_Hab.naiveBayes
summary(SS_L2_Hab.naiveBayes)
str(SS_L2_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/SS_L2_Hab.txt")
SS_L2_Hab.naiveBayes 
sink()


true.typeSS = as.factor(SStest[,14])
predictedSS = predict(SS_L2_Hab.naiveBayes, SStest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeSS,predictedSS), "11_NB_SS_Lv2_MisclassMatrix.csv")

PredictionSS_L2_Hab <- predict(SS_L2_Hab.naiveBayes, SStest)
submitSS_L2_Hab <- data.frame(HabType = SStest$L2_Hab, PredictedSS_L2_Hab = PredictionSS_L2_Hab, 
                              X = SStest$Lat, Y = SStest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitSS_L2_Hab, file = "SS_L2_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

SS_L2_Hab.NB.predict <- predict(SS_L2_Hab.naiveBayes, SSpoints, type="class")
SS_L2_Hab.predict <- as.data.frame(SS_L2_Hab.NB.predict)
pred.SS_L2_Hab <- as.data.frame(cbind(SSpoints$Long, SSpoints$Lat, SS_L2_Hab.predict))
pred.SS_L2_Hab$SS_L2_Hab.NB.predict <- as.numeric(as.character(pred.SS_L2_Hab$SS_L2_Hab.NB.predict))
names(pred.SS_L2_Hab) <- c("X","Y", "predSS_L2_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv2Outputs")

coordinates(pred.SS_L2_Hab) <- ~X+Y
extSS <- extent(pred.SS_L2_Hab)
rSS <- raster(ext=extSS,res=0.000048500000005447)
to_asciiSS <- rasterize(pred.SS_L2_Hab, rSS, 'predSS_L2_Hab')
writeRaster(to_asciiSS,'SS_L2_HabNB.asc', format='ascii', overwrite =TRUE)


```








```{r}


##########################
#### LEVEL 3 HABITATS ####
##########################

setwd("C:/OneDrive/C3_Map/NB_Outputs/Figures")
set.seed(415)

L3_Hab.naiveBayes <- naiveBayes(as.factor(L3_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= model)

L3_Hab.naiveBayes
summary(L3_Hab.naiveBayes)
str(L3_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/ALL_L3_Hab.txt")
L3_Hab.naiveBayes 
sink()


true.type = as.factor(test[,15])
predicted = predict(L3_Hab.naiveBayes, test,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.type,predicted), "3_NB_Lv3_MisclassMatrix.csv")

# need to edit, look at http://trevorstephens.com/kaggle-titanic-tutorial/r-part-5-random-forests/
PredictionL3_Hab <- predict(L3_Hab.naiveBayes, test)
submitL3_Hab <- data.frame(HabType = test$L3_Hab, PredictedL3_Hab = PredictionL3_Hab, X = test$Lat, Y = test$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitL3_Hab, file = "L3_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

L3_Hab.NB.predict <- predict(L3_Hab.naiveBayes, points1, type="class")
L3_Hab.predict <- as.data.frame(L3_Hab.NB.predict)
pred.L3_Hab <- as.data.frame(cbind(points1$Long, points1$Lat, L3_Hab.predict))
pred.L3_Hab$L3_Hab.NB.predict <- as.numeric(as.character(pred.L3_Hab$L3_Hab.NB.predict))
names(pred.L3_Hab) <- c("X","Y", "predL3_Hab")


L3_Hab.NB.predict2 <- predict(L3_Hab.naiveBayes, points2, type="class")
L3_Hab.predict2 <- as.data.frame(L3_Hab.NB.predict2)
pred.L3_Hab2 <- as.data.frame(cbind(points2$Long, points2$Lat,  L3_Hab.predict2))
pred.L3_Hab2$L3_Hab.NB.predict2 <- as.numeric(as.character(pred.L3_Hab2$L3_Hab.NB.predict2))
names(pred.L3_Hab2) <- c("X","Y", "predL3_Hab")

L3_Hab.NB.predict3 <- predict(L3_Hab.naiveBayes, points3, type="class")
L3_Hab.predict3 <- as.data.frame(L3_Hab.NB.predict3)
pred.L3_Hab3 <- as.data.frame(cbind(points3$Long, points3$Lat,  L3_Hab.predict3))
pred.L3_Hab3$L3_Hab.NB.predict3 <- as.numeric(as.character(pred.L3_Hab3$L3_Hab.NB.predict3))
names(pred.L3_Hab3) <- c("X","Y", "predL3_Hab")

############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv3Outputs")

coordinates(pred.L3_Hab) <- ~X+Y
ext <- extent(pred.L3_Hab)
r <- raster(ext=ext,res=0.0000483000000031097)
to_ascii <- rasterize(pred.L3_Hab, r, 'predL3_Hab')
writeRaster(to_ascii,'L3_HabNB.asc', format='ascii', overwrite =TRUE)

coordinates(pred.L3_Hab2) <- ~X+Y
ext2 <- extent(pred.L3_Hab2)
r2 <- raster(ext=ext2,res=0.0000483000000031097)
to_ascii2 <- rasterize(pred.L3_Hab2, r2, 'predL3_Hab')
writeRaster(to_ascii2,'L3_HabNB2.asc', format='ascii', overwrite =TRUE)

coordinates(pred.L3_Hab3) <- ~X+Y
ext3 <- extent(pred.L3_Hab3)
r3 <- raster(ext=ext3,res=0.0000483000000031097)
to_ascii3 <- rasterize(pred.L3_Hab3, r3, 'predL3_Hab')
writeRaster(to_ascii3,'L3_HabNB3.asc', format='ascii', overwrite =TRUE)


#################
## HELBY BANKS ##
#################

HB_L3_Hab.naiveBayes <- naiveBayes(as.factor(L3_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= HBmodel)

HB_L3_Hab.naiveBayes
summary(HB_L3_Hab.naiveBayes)
str(HB_L3_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/HB_L3_Hab.txt")
HB_L3_Hab.naiveBayes 
sink()


true.typeHB = as.factor(HBtest[,15])
predictedHB = predict(HB_L3_Hab.naiveBayes, HBtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeHB,predictedHB), "12_NB_HB_Lv3_MisclassMatrix.csv")

PredictionHB_L3_Hab <- predict(HB_L3_Hab.naiveBayes, HBtest)
submitHB_L3_Hab <- data.frame(HabType = HBtest$L3_Hab, PredictedHB_L3_Hab = PredictionHB_L3_Hab, 
                              X = HBtest$Lat, Y = HBtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitHB_L3_Hab, file = "HB_L3_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

HB_L3_Hab.NB.predict <- predict(HB_L3_Hab.naiveBayes, HBpoints, type="class")
HB_L3_Hab.predict <- as.data.frame(HB_L3_Hab.NB.predict)
pred.HB_L3_Hab <- as.data.frame(cbind(HBpoints$Long, HBpoints$Lat, HB_L3_Hab.predict))
pred.HB_L3_Hab$HB_L3_Hab.NB.predict <- as.numeric(as.character(pred.HB_L3_Hab$HB_L3_Hab.NB.predict))
names(pred.HB_L3_Hab) <- c("X","Y", "predHB_L3_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv3Outputs")

coordinates(pred.HB_L3_Hab) <- ~X+Y
extHB <- extent(pred.HB_L3_Hab)
rHB <- raster(ext=extHB,res=0.0000483000000031097)
to_asciiHB <- rasterize(pred.HB_L3_Hab, rHB, 'predHB_L3_Hab')
writeRaster(to_asciiHB,'HB_L3_HabNB.asc', format='ascii', overwrite =TRUE)




################
## TANTABIDDI ##
################

TB_L3_Hab.naiveBayes <- naiveBayes(as.factor(L3_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= TBmodel)

TB_L3_Hab.naiveBayes
summary(TB_L3_Hab.naiveBayes)
str(TB_L3_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/TB_L3_Hab.txt")
TB_L3_Hab.naiveBayes 
sink()


true.typeTB = as.factor(TBtest[,15])
predictedTB = predict(TB_L3_Hab.naiveBayes, TBtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeTB,predictedTB), "13_NB_TB_Lv3_MisclassMatrix.csv")

PredictionTB_L3_Hab <- predict(TB_L3_Hab.naiveBayes, TBtest)
submitTB_L3_Hab <- data.frame(HabType = TBtest$L3_Hab, PredictedTB_L3_Hab = PredictionTB_L3_Hab, 
                              X = TBtest$Lat, Y = TBtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitTB_L3_Hab, file = "TB_L3_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

TB_L3_Hab.NB.predict <- predict(TB_L3_Hab.naiveBayes, TBpoints, type="class")
TB_L3_Hab.predict <- as.data.frame(TB_L3_Hab.NB.predict)
pred.TB_L3_Hab <- as.data.frame(cbind(TBpoints$Long, TBpoints$Lat, TB_L3_Hab.predict))
pred.TB_L3_Hab$TB_L3_Hab.NB.predict <- as.numeric(as.character(pred.TB_L3_Hab$TB_L3_Hab.NB.predict))
names(pred.TB_L3_Hab) <- c("X","Y", "predTB_L3_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv3Outputs")

coordinates(pred.TB_L3_Hab) <- ~X+Y
extTB <- extent(pred.TB_L3_Hab)
rTB <- raster(ext=extTB,res=0.0000483000000031097)
to_asciiTB <- rasterize(pred.TB_L3_Hab, rTB, 'predTB_L3_Hab')
writeRaster(to_asciiTB,'TB_L3_HabNB.asc', format='ascii', overwrite =TRUE)


##############
## MANGROVE ##
##############

MG_L3_Hab.naiveBayes <- naiveBayes(as.factor(L3_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= MGmodel)

MG_L3_Hab.naiveBayes
summary(MG_L3_Hab.naiveBayes)
str(MG_L3_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/MG_L3_Hab.txt")
MG_L3_Hab.naiveBayes 
sink()


true.typeMG = as.factor(MGtest[,15])
predictedMG = predict(MG_L3_Hab.naiveBayes, MGtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeMG,predictedMG), "14_NB_MG_Lv3_MisclassMatrix.csv")

PredictionMG_L3_Hab <- predict(MG_L3_Hab.naiveBayes, MGtest)
submitMG_L3_Hab <- data.frame(HabType = MGtest$L3_Hab, PredictedMG_L3_Hab = PredictionMG_L3_Hab, 
                              X = MGtest$Lat, Y = MGtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitMG_L3_Hab, file = "MG_L3_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

MG_L3_Hab.NB.predict <- predict(MG_L3_Hab.naiveBayes, MGpoints, type="class")
MG_L3_Hab.predict <- as.data.frame(MG_L3_Hab.NB.predict)
pred.MG_L3_Hab <- as.data.frame(cbind(MGpoints$Long, MGpoints$Lat, MG_L3_Hab.predict))
pred.MG_L3_Hab$MG_L3_Hab.NB.predict <- as.numeric(as.character(pred.MG_L3_Hab$MG_L3_Hab.NB.predict))
names(pred.MG_L3_Hab) <- c("X","Y", "predMG_L3_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv3Outputs")

coordinates(pred.MG_L3_Hab) <- ~X+Y
extMG <- extent(pred.MG_L3_Hab)
rMG <- raster(ext=extMG,res=0.0000483000000031097)
to_asciiMG <- rasterize(pred.MG_L3_Hab, rMG, 'predMG_L3_Hab')
writeRaster(to_asciiMG,'MG_L3_HabNB.asc', format='ascii', overwrite =TRUE)




###################
## SOUTHERN SITE ##
###################

SS_L3_Hab.naiveBayes <- naiveBayes(as.factor(L3_Hab) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= SSmodel)

SS_L3_Hab.naiveBayes
summary(SS_L3_Hab.naiveBayes)
str(SS_L3_Hab.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/SS_L3_Hab.txt")
SS_L3_Hab.naiveBayes 
sink()


true.typeSS = as.factor(SStest[,15])
predictedSS = predict(SS_L3_Hab.naiveBayes, SStest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeSS,predictedSS), "15_NB_SS_Lv2_MisclassMatrix.csv")

PredictionSS_L3_Hab <- predict(SS_L3_Hab.naiveBayes, SStest)
submitSS_L3_Hab <- data.frame(HabType = SStest$L3_Hab, PredictedSS_L3_Hab = PredictionSS_L3_Hab, 
                              X = SStest$Lat, Y = SStest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitSS_L3_Hab, file = "SS_L3_HabnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

SS_L3_Hab.NB.predict <- predict(SS_L3_Hab.naiveBayes, SSpoints, type="class")
SS_L3_Hab.predict <- as.data.frame(SS_L3_Hab.NB.predict)
pred.SS_L3_Hab <- as.data.frame(cbind(SSpoints$Long, SSpoints$Lat, SS_L3_Hab.predict))
pred.SS_L3_Hab$SS_L3_Hab.NB.predict <- as.numeric(as.character(pred.SS_L3_Hab$SS_L3_Hab.NB.predict))
names(pred.SS_L3_Hab) <- c("X","Y", "predSS_L3_Hab")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv3Outputs")

coordinates(pred.SS_L3_Hab) <- ~X+Y
extSS <- extent(pred.SS_L3_Hab)
rSS <- raster(ext=extSS,res=0.000048500000005447)
to_asciiSS <- rasterize(pred.SS_L3_Hab, rSS, 'predSS_L3_Hab')
writeRaster(to_asciiSS,'SS_L3_HabNB.asc', format='ascii', overwrite =TRUE)

```




```{r}


##############################
#### LEVEL 3 EDIT HABITATS ####
##############################

setwd("C:/OneDrive/C3_Map/NB_Outputs/Figures")
set.seed(415)

L3_Hab_EDIT.naiveBayes <- naiveBayes(as.factor(L3_Hab_EDIT) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= model)

L3_Hab_EDIT.naiveBayes
summary(L3_Hab_EDIT.naiveBayes)
str(L3_Hab_EDIT.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/ALL_L3_Hab_EDIT.txt")
L3_Hab_EDIT.naiveBayes 
sink()


true.type = as.factor(test[,16])
predicted = predict(L3_Hab_EDIT.naiveBayes, test,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.type,predicted), "16_NB_Lv3_EDIT_MisclassMatrix.csv")

# need to edit, look at http://trevorstephens.com/kaggle-titanic-tutorial/r-part-5-random-forests/
PredictionL3_Hab_EDIT <- predict(L3_Hab_EDIT.naiveBayes, test)
submitL3_Hab_EDIT <- data.frame(HabType = test$L3_Hab_EDIT, PredictedL3_Hab_EDIT = PredictionL3_Hab_EDIT, X = test$Lat, Y = test$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitL3_Hab_EDIT, file = "L3_Hab_EDITnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

L3_Hab_EDIT.NB.predict <- predict(L3_Hab_EDIT.naiveBayes, points1, type="class")
L3_Hab_EDIT.predict <- as.data.frame(L3_Hab_EDIT.NB.predict)
pred.L3_Hab_EDIT <- as.data.frame(cbind(points1$Long, points1$Lat, L3_Hab_EDIT.predict))
pred.L3_Hab_EDIT$L3_Hab_EDIT.NB.predict <- as.numeric(as.character(pred.L3_Hab_EDIT$L3_Hab_EDIT.NB.predict))
names(pred.L3_Hab_EDIT) <- c("X","Y", "predL3_Hab_EDIT")


L3_Hab_EDIT.NB.predict2 <- predict(L3_Hab_EDIT.naiveBayes, points2, type="class")
L3_Hab_EDIT.predict2 <- as.data.frame(L3_Hab_EDIT.NB.predict2)
pred.L3_Hab_EDIT2 <- as.data.frame(cbind(points2$Long, points2$Lat,  L3_Hab_EDIT.predict2))
pred.L3_Hab_EDIT2$L3_Hab_EDIT.NB.predict2 <- as.numeric(as.character(pred.L3_Hab_EDIT2$L3_Hab_EDIT.NB.predict2))
names(pred.L3_Hab_EDIT2) <- c("X","Y", "predL3_Hab_EDIT")

L3_Hab_EDIT.NB.predict3 <- predict(L3_Hab_EDIT.naiveBayes, points3, type="class")
L3_Hab_EDIT.predict3 <- as.data.frame(L3_Hab_EDIT.NB.predict3)
pred.L3_Hab_EDIT3 <- as.data.frame(cbind(points3$Long, points3$Lat,  L3_Hab_EDIT.predict3))
pred.L3_Hab_EDIT3$L3_Hab_EDIT.NB.predict3 <- as.numeric(as.character(pred.L3_Hab_EDIT3$L3_Hab_EDIT.NB.predict3))
names(pred.L3_Hab_EDIT3) <- c("X","Y", "predL3_Hab_EDIT")

############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv3EDITOutputs")

coordinates(pred.L3_Hab_EDIT) <- ~X+Y
ext <- extent(pred.L3_Hab_EDIT)
r <- raster(ext=ext,res=0.0000483000000031097)
to_ascii <- rasterize(pred.L3_Hab_EDIT, r, 'predL3_Hab_EDIT')
writeRaster(to_ascii,'L3_Hab_EDITNB.asc', format='ascii', overwrite =TRUE)

coordinates(pred.L3_Hab_EDIT2) <- ~X+Y
ext2 <- extent(pred.L3_Hab_EDIT2)
r2 <- raster(ext=ext2,res=0.0000483000000031097)
to_ascii2 <- rasterize(pred.L3_Hab_EDIT2, r2, 'predL3_Hab_EDIT')
writeRaster(to_ascii2,'L3_Hab_EDITNB2.asc', format='ascii', overwrite =TRUE)

coordinates(pred.L3_Hab_EDIT3) <- ~X+Y
ext3 <- extent(pred.L3_Hab_EDIT3)
r3 <- raster(ext=ext3,res=0.0000483000000031097)
to_ascii3 <- rasterize(pred.L3_Hab_EDIT3, r3, 'predL3_Hab_EDIT')
writeRaster(to_ascii3,'L3_Hab_EDITNB3.asc', format='ascii', overwrite =TRUE)


#################
## HELBY BANKS ##
#################

HB_L3_Hab_EDIT.naiveBayes <- naiveBayes(as.factor(L3_Hab_EDIT) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	
                                          mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= HBmodel)

HB_L3_Hab_EDIT.naiveBayes
summary(HB_L3_Hab_EDIT.naiveBayes)
str(HB_L3_Hab_EDIT.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/HB_L3_Hab_EDIT.txt")
HB_L3_Hab_EDIT.naiveBayes 
sink()


true.typeHB = as.factor(HBtest[,16])
predictedHB = predict(HB_L3_Hab_EDIT.naiveBayes, HBtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeHB,predictedHB), "17_NB_HB_Lv3_EDIT_MisclassMatrix.csv")

PredictionHB_L3_Hab_EDIT <- predict(HB_L3_Hab_EDIT.naiveBayes, HBtest)
submitHB_L3_Hab_EDIT <- data.frame(HabType = HBtest$L3_Hab_EDIT, PredictedHB_L3_Hab_EDIT = PredictionHB_L3_Hab_EDIT, 
                              X = HBtest$Lat, Y = HBtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitHB_L3_Hab_EDIT, file = "HB_L3_Hab_EDITnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

HB_L3_Hab_EDIT.NB.predict <- predict(HB_L3_Hab_EDIT.naiveBayes, HBpoints, type="class")
HB_L3_Hab_EDIT.predict <- as.data.frame(HB_L3_Hab_EDIT.NB.predict)
pred.HB_L3_Hab_EDIT <- as.data.frame(cbind(HBpoints$Long, HBpoints$Lat, HB_L3_Hab_EDIT.predict))
pred.HB_L3_Hab_EDIT$HB_L3_Hab_EDIT.NB.predict <- as.numeric(as.character(pred.HB_L3_Hab_EDIT$HB_L3_Hab_EDIT.NB.predict))
names(pred.HB_L3_Hab_EDIT) <- c("X","Y", "predHB_L3_Hab_EDIT")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv3EDITOutputs")

coordinates(pred.HB_L3_Hab_EDIT) <- ~X+Y
extHB <- extent(pred.HB_L3_Hab_EDIT)
rHB <- raster(ext=extHB,res=0.0000483000000031097)
to_asciiHB <- rasterize(pred.HB_L3_Hab_EDIT, rHB, 'predHB_L3_Hab_EDIT')
writeRaster(to_asciiHB,'HB_L3_Hab_EDITNB.asc', format='ascii', overwrite =TRUE)




################
## TANTABIDDI ##
################

TB_L3_Hab_EDIT.naiveBayes <- naiveBayes(as.factor(L3_Hab_EDIT) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= TBmodel)

TB_L3_Hab_EDIT.naiveBayes
summary(TB_L3_Hab_EDIT.naiveBayes)
str(TB_L3_Hab_EDIT.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/TB_L3_Hab_EDIT.txt")
TB_L3_Hab_EDIT.naiveBayes 
sink()


true.typeTB = as.factor(TBtest[,16])
predictedTB = predict(TB_L3_Hab_EDIT.naiveBayes, TBtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeTB,predictedTB), "18_NB_TB_Lv3_EDIT_MisclassMatrix.csv")

PredictionTB_L3_Hab_EDIT <- predict(TB_L3_Hab_EDIT.naiveBayes, TBtest)
submitTB_L3_Hab_EDIT <- data.frame(HabType = TBtest$L3_Hab_EDIT, PredictedTB_L3_Hab_EDIT = PredictionTB_L3_Hab_EDIT, 
                              X = TBtest$Lat, Y = TBtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitTB_L3_Hab_EDIT, file = "TB_L3_Hab_EDITnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

TB_L3_Hab_EDIT.NB.predict <- predict(TB_L3_Hab_EDIT.naiveBayes, TBpoints, type="class")
TB_L3_Hab_EDIT.predict <- as.data.frame(TB_L3_Hab_EDIT.NB.predict)
pred.TB_L3_Hab_EDIT <- as.data.frame(cbind(TBpoints$Long, TBpoints$Lat, TB_L3_Hab_EDIT.predict))
pred.TB_L3_Hab_EDIT$TB_L3_Hab_EDIT.NB.predict <- as.numeric(as.character(pred.TB_L3_Hab_EDIT$TB_L3_Hab_EDIT.NB.predict))
names(pred.TB_L3_Hab_EDIT) <- c("X","Y", "predTB_L3_Hab_EDIT")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv3EDITOutputs")

coordinates(pred.TB_L3_Hab_EDIT) <- ~X+Y
extTB <- extent(pred.TB_L3_Hab_EDIT)
rTB <- raster(ext=extTB,res=0.0000483000000031097)
to_asciiTB <- rasterize(pred.TB_L3_Hab_EDIT, rTB, 'predTB_L3_Hab_EDIT')
writeRaster(to_asciiTB,'TB_L3_Hab_EDITNB.asc', format='ascii', overwrite =TRUE)


##############
## MANGROVE ##
##############

MG_L3_Hab_EDIT.naiveBayes <- naiveBayes(as.factor(L3_Hab_EDIT) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= MGmodel)

MG_L3_Hab_EDIT.naiveBayes
summary(MG_L3_Hab_EDIT.naiveBayes)
str(MG_L3_Hab_EDIT.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/MG_L3_Hab_EDIT.txt")
MG_L3_Hab_EDIT.naiveBayes 
sink()


true.typeMG = as.factor(MGtest[,16])
predictedMG = predict(MG_L3_Hab_EDIT.naiveBayes, MGtest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeMG,predictedMG), "19_NB_MG_Lv3_EDIT_MisclassMatrix.csv")

PredictionMG_L3_Hab_EDIT <- predict(MG_L3_Hab_EDIT.naiveBayes, MGtest)
submitMG_L3_Hab_EDIT <- data.frame(HabType = MGtest$L3_Hab_EDIT, PredictedMG_L3_Hab_EDIT = PredictionMG_L3_Hab_EDIT, 
                              X = MGtest$Lat, Y = MGtest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitMG_L3_Hab_EDIT, file = "MG_L3_Hab_EDITnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

MG_L3_Hab_EDIT.NB.predict <- predict(MG_L3_Hab_EDIT.naiveBayes, MGpoints, type="class")
MG_L3_Hab_EDIT.predict <- as.data.frame(MG_L3_Hab_EDIT.NB.predict)
pred.MG_L3_Hab_EDIT <- as.data.frame(cbind(MGpoints$Long, MGpoints$Lat, MG_L3_Hab_EDIT.predict))
pred.MG_L3_Hab_EDIT$MG_L3_Hab_EDIT.NB.predict <- as.numeric(as.character(pred.MG_L3_Hab_EDIT$MG_L3_Hab_EDIT.NB.predict))
names(pred.MG_L3_Hab_EDIT) <- c("X","Y", "predMG_L3_Hab_EDIT")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv3EDITOutputs")

coordinates(pred.MG_L3_Hab_EDIT) <- ~X+Y
extMG <- extent(pred.MG_L3_Hab_EDIT)
rMG <- raster(ext=extMG,res=0.0000483000000031097)
to_asciiMG <- rasterize(pred.MG_L3_Hab_EDIT, rMG, 'predMG_L3_Hab_EDIT')
writeRaster(to_asciiMG,'MG_L3_Hab_EDITNB.asc', format='ascii', overwrite =TRUE)




###################
## SOUTHERN SITE ##
###################

SS_L3_Hab_EDIT.naiveBayes <- naiveBayes(as.factor(L3_Hab_EDIT) ~ curv +	curv_plan +	curv_prof +	slope +	mean3 +	mean5 +	mean10 +
                       mean25 +	std3 +	std5 +	std10 +	std25 +	range3 +	range5 +	range10 +	range25 +
                       hyp3 +	hyp5 +	hyp10 +	hyp25 +	rugosity +	east +	north +	BPI_F_10 +	BPI_F_15 +
                       BPI_F_25 +	BPI_B_50 +	BPI_B_100 +	BPI_B_250 +	Depth + BScatter,
                     data= SSmodel)

SS_L3_Hab_EDIT.naiveBayes
summary(SS_L3_Hab_EDIT.naiveBayes)
str(SS_L3_Hab_EDIT.naiveBayes)
sink("C:/OneDrive/C3_Map/NB_Outputs/Figures/SS_L3_Hab_EDIT.txt")
SS_L3_Hab_EDIT.naiveBayes 
sink()


true.typeSS = as.factor(SStest[,16])
predictedSS = predict(SS_L3_Hab_EDIT.naiveBayes, SStest,type="class")
table(true.type,predicted)
setwd("C:/OneDrive/C3_Map/NB_Outputs/BER")
write.csv(table(true.typeSS,predictedSS), "20_NB_SS_Lv3_EDIT_MisclassMatrix.csv")

PredictionSS_L3_Hab_EDIT <- predict(SS_L3_Hab_EDIT.naiveBayes, SStest)
submitSS_L3_Hab_EDIT <- data.frame(HabType = SStest$L3_Hab_EDIT, PredictedSS_L3_Hab_EDIT = PredictionSS_L3_Hab_EDIT, 
                              X = SStest$Lat, Y = SStest$Long)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")
write.csv(submitSS_L3_Hab_EDIT, file = "SS_L3_Hab_EDITnaiveBayes.csv", row.names = FALSE)


#############
## PREDICT ##
############

SS_L3_Hab_EDIT.NB.predict <- predict(SS_L3_Hab_EDIT.naiveBayes, SSpoints, type="class")
SS_L3_Hab_EDIT.predict <- as.data.frame(SS_L3_Hab_EDIT.NB.predict)
pred.SS_L3_Hab_EDIT <- as.data.frame(cbind(SSpoints$Long, SSpoints$Lat, SS_L3_Hab_EDIT.predict))
pred.SS_L3_Hab_EDIT$SS_L3_Hab_EDIT.NB.predict <- as.numeric(as.character(pred.SS_L3_Hab_EDIT$SS_L3_Hab_EDIT.NB.predict))
names(pred.SS_L3_Hab_EDIT) <- c("X","Y", "predSS_L3_Hab_EDIT")


############
## OUTPUT ##
############

setwd("C:/OneDrive/C3_Map/NB_Outputs/Lv3EDITOutputs")

coordinates(pred.SS_L3_Hab_EDIT) <- ~X+Y
extSS <- extent(pred.SS_L3_Hab_EDIT)
rSS <- raster(ext=extSS,res=0.000048500000005447)
to_asciiSS <- rasterize(pred.SS_L3_Hab_EDIT, rSS, 'predSS_L3_Hab_EDIT')
writeRaster(to_asciiSS,'SS_L3_Hab_EDITNB.asc', format='ascii', overwrite =TRUE)

```



```{r}

#################
## AUC CURVES ##
#################

library(ROCR)
setwd("C:/OneDrive/C3_Map/NB_Outputs/ROCtests")

filenames <- list.files()  
for (i in filenames) {  
   name <- gsub("-",".",i)
   name <- gsub(".csv","",name)  
   i <- paste(".\\",i,sep="")
   assign(name,read.csv(i, header=TRUE))
} 


predictL1ALL <- prediction(as.numeric(as.character(L1_HabnaiveBayes$PredictedL1_Hab)), L1_HabnaiveBayes$HabType)
perfL1ALL <- performance(predictL1ALL, measure = "tpr", x.measure = "fpr")
plot(perfL1ALL, mean = "ROC curve for L1 ALL",
     col = "blue", lwd = 3)
abline(a=0, b=1, lwd = 2, lty = 2)
perf.aucL1ALL <- performance(predictL1ALL, measure = "auc")
str(perf.aucL1ALL)
unlist(perf.aucL1ALL@y.values)

predictL1HB <- prediction(as.numeric(as.character(HB_L1_HabnaiveBayes$PredictedHB_L1_Hab)), HB_L1_HabnaiveBayes$HabType)
perfL1HB <- performance(predictL1HB, measure = "tpr", x.measure = "fpr")
plot(perfL1HB, mean = "ROC curve for L1 HB",
     col = "blue", lwd = 3)
abline(a=0, b=1, lwd = 2, lty = 2)
perf.aucL1HB <- performance(predictL1HB, measure = "auc")
str(perf.aucL1HB)
unlist(perf.aucL1HB@y.values)

predictL1TB <- prediction(as.numeric(as.character(TB_L1_HabnaiveBayes$PredictedTB_L1_Hab)), TB_L1_HabnaiveBayes$HabType)
perfL1TB <- performance(predictL1TB, measure = "tpr", x.measure = "fpr")
plot(perfL1TB, mean = "ROC curve for L1 TB",
     col = "blue", lwd = 3)
abline(a=0, b=1, lwd = 2, lty = 2)
perf.aucL1TB <- performance(predictL1TB, measure = "auc")
str(perf.aucL1TB)
unlist(perf.aucL1TB@y.values)

predictL1MG <- prediction(as.numeric(as.character(MG_L1_HabnaiveBayes$PredictedMG_L1_Hab)), MG_L1_HabnaiveBayes$HabType)
perfL1MG <- performance(predictL1MG, measure = "tpr", x.measure = "fpr")
plot(perfL1MG, mean = "ROC curve for L1 MG",
     col = "blue", lwd = 3)
abline(a=0, b=1, lwd = 2, lty = 2)
perf.aucL1MG <- performance(predictL1MG, measure = "auc")
str(perf.aucL1MG)
unlist(perf.aucL1MG@y.values)

predictL1SS <- prediction(as.numeric(as.character(SS_L1_HabnaiveBayes$PredictedSS_L1_Hab)), SS_L1_HabnaiveBayes$HabType)
perfL1SS <- performance(predictL1SS, measure = "tpr", x.measure = "fpr")
plot(perfL1SS, mean = "ROC curve for L1 SS",
     col = "blue", lwd = 3)
abline(a=0, b=1, lwd = 2, lty = 2)
perf.aucL1SS <- performance(predictL1SS, measure = "auc")
str(perf.aucL1SS)
unlist(perf.aucL1SS@y.values)


```
